import type { Job } from "../../types";

export const jobs: Job[] = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "TechNova",
    location: "Kathmandu, NP",
    category: "Engineering",
    type: "Full-time",
    salary: 60000,
    description: "Build and maintain user-facing features using React and TypeScript.",
    requirements: ["React", "TypeScript", "CSS"],
    postedAt: "2026-08-01T09:00:00.000Z",
  },
  {
    id: 2,
    title: "Backend Developer",
    company: "CloudWorks",
    location: "Biratnagar, NP",
    category: "Engineering",
    type: "Full-time",
    salary: 70000,
    description: "Design and implement REST APIs and services using Node.js.",
    requirements: ["Node.js", "PostgreSQL", "Docker"],
    postedAt: "2026-08-05T09:00:00.000Z",
  },
  {
    id: 3,
    title: "UI/UX Designer",
    company: "PixelForge",
    location: "Remote",
    category: "Design",
    type: "Contract",
    salary: 45000,
    description: "Craft delightful, accessible interfaces for web and mobile apps.",
    requirements: ["Figma", "Prototyping", "User Research"],
    postedAt: "2026-08-10T09:00:00.000Z",
  },
  {
    id: 4,
    title: "Full Stack Developer",
    company: "CodeCraft Labs",
    location: "Pokhara, NP",
    category: "Engineering",
    type: "Full-time",
    salary: 75000,
    description: "Develop end-to-end web applications with modern frontend and backend technologies.",
    requirements: ["React", "Node.js", "MongoDB", "TypeScript"],
    postedAt: "2026-08-12T09:00:00.000Z",
  },
  {
    id: 5,
    title: "DevOps Engineer",
    company: "InfraScale",
    location: "Kathmandu, NP",
    category: "Engineering",
    type: "Full-time",
    salary: 80000,
    description: "Manage CI/CD pipelines, cloud infrastructure, and ensure system reliability.",
    requirements: ["AWS", "Kubernetes", "Terraform", "Docker"],
    postedAt: "2026-08-14T09:00:00.000Z",
  },
  {
    id: 6,
    title: "Mobile App Developer",
    company: "AppVista",
    location: "Lalitpur, NP",
    category: "Engineering",
    type: "Full-time",
    salary: 65000,
    description: "Build high-performance iOS and Android applications using Flutter.",
    requirements: ["Flutter", "Dart", "Firebase", "REST APIs"],
    postedAt: "2026-08-16T09:00:00.000Z",
  },
  {
    id: 7,
    title: "Data Analyst",
    company: "InsightMetrics",
    location: "Remote",
    category: "Data",
    type: "Full-time",
    salary: 55000,
    description: "Analyze large datasets and create actionable insights with visualizations.",
    requirements: ["SQL", "Python", "Tableau", "Excel"],
    postedAt: "2026-08-18T09:00:00.000Z",
  },
  {
    id: 8,
    title: "QA Engineer",
    company: "BugFree Solutions",
    location: "Biratnagar, NP",
    category: "Engineering",
    type: "Contract",
    salary: 50000,
    description: "Design and execute test plans to ensure software quality and reliability.",
    requirements: ["Selenium", "Cypress", "Jest", "API Testing"],
    postedAt: "2026-08-20T09:00:00.000Z",
  },
  {
    id: 9,
    title: "Product Manager",
    company: "NovaPath",
    location: "Kathmandu, NP",
    category: "Product",
    type: "Full-time",
    salary: 85000,
    description: "Define product roadmap, prioritize features, and collaborate with engineering & design teams.",
    requirements: ["Agile", "Roadmapping", "User Stories", "Analytics"],
    postedAt: "2026-08-22T09:00:00.000Z",
  },
  {
    id: 10,
    title: "Digital Marketing Specialist",
    company: "GrowthHive",
    location: "Remote",
    category: "Marketing",
    type: "Part-time",
    salary: 40000,
    description: "Plan and execute digital campaigns across social media, SEO, and paid ads.",
    requirements: ["SEO", "Google Ads", "Social Media", "Analytics"],
    postedAt: "2026-08-24T09:00:00.000Z",
  },
];


export const getAllJobs = async():Promise<Job[]>=>{
    return jobs
    
}



